### PR TITLE
Update quickstart with new solr command

### PR DESCRIPTION
**Pull request by skorper**
I was running through the quickstart and found the `ZK_HOST` environment variable wasn't being used by the solr container, resulting in failure. By updating to `SDAP_ZK_SERVICE_HOST` the solr container ran successfully.

### CODE REVIEW

**Comment by RKuttruff** [comment]
This is odd, my existing deployment with Docker uses `ZK_HOST` without issue. What kind of error were you seeing?

**Comment by skorper** [comment]
I can try to recreate the issue a bit later. But in summary, the solr container failed to launch because it could not find the zookeeper host. It seemed like `ZK_HOST` was being totally ignored. To confirm this, I changed the port in `ZK_HOST` and noticed the solr container was still attempting to access zookeeper at the old port. When inspecting the solr container I noticed there were other ZK related env vars and played around with it until I found something that worked. I'll post a follow-up with logs and more details soon

**Comment by RKuttruff** [comment]
Thinking on this, it may be a good idea to provide both commands and inform the user that if one does not work, try the other.

**Review by ngachung — APPROVED** [review]
According to this thread https://lists.apache.org/thread/3n2tdsll202z644r4w8x8wb6c0f3o1n0 this change resolved the issue user was encountering, so I think we should merge this.

**Review by RKuttruff — APPROVED** [review]
Looks good
Renewing approval after fixing merge conflict w/ changelog

**Pull request merged**
